language: clojure
lein: lein2
services:
  - elasticsearch
env:
  - ES_CLUSTER_NAME=elasticsearch ES_HOST=localhost ES_REST_PORT=9200 ES_BINARY_PORT=9300
before_install:
  - "ulimit -u 4096"
  - "sudo service elasticsearch status"
script: lein2 test
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

